//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPay.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CodeType()
        {
            this.CodeDetails = new HashSet<CodeDetail>();
        }
    
        public int RecordID { get; set; }
        public string CodeTypeID { get; set; }
        public string Description { get; set; }
        public string SourceID { get; set; }
        public Nullable<bool> IsInactive { get; set; }
        public string ItemCodeRef { get; set; }
        public Nullable<int> ParentID { get; set; }
        public System.Guid GlobalID { get; set; }
        public Nullable<System.DateTime> AuditDateTime { get; set; }
        public string AuditUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodeDetail> CodeDetails { get; set; }
    }
}
