//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPay.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int RecordID { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string EmailAddress { get; set; }
        public string WebPage { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerSalutation { get; set; }
        public string CustomerTypeID { get; set; }
        public string TaxNo { get; set; }
        public string VATNumber { get; set; }
        public string CurrencyID { get; set; }
        public string GLSalesAccount { get; set; }
        public string TermsID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string TaxGroupID { get; set; }
        public string CreditRating { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string CreditComments { get; set; }
        public Nullable<System.DateTime> SignedUpDate { get; set; }
        public Nullable<bool> Statements { get; set; }
        public Nullable<int> BillCycleCode { get; set; }
        public string SpecialInstructions { get; set; }
        public Nullable<int> AccountStatus { get; set; }
        public string StatusComment { get; set; }
        public string RegionID { get; set; }
        public string SourceID { get; set; }
        public string IndustryID { get; set; }
        public Nullable<bool> Confirmed { get; set; }
        public Nullable<bool> IsMistCust { get; set; }
        public Nullable<int> ParentID { get; set; }
        public System.Guid GlobalID { get; set; }
        public Nullable<System.DateTime> AuditDateTime { get; set; }
        public string AuditUserID { get; set; }
    }
}
