//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPay.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MPayEntities : DbContext
    {
        public MPayEntities()
            : base("name=MPayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CodeDetail> CodeDetails { get; set; }
        public virtual DbSet<CodeType> CodeTypes { get; set; }
        public virtual DbSet<CTAddress> CTAddresses { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<InventoryItem> InventoryItems { get; set; }
        public virtual DbSet<LedgerChartOfAccount> LedgerChartOfAccounts { get; set; }
        public virtual DbSet<SmTableControl> SmTableControls { get; set; }
        public virtual DbSet<SRClass> SRClasses { get; set; }
        public virtual DbSet<SRClassArm> SRClassArms { get; set; }
        public virtual DbSet<SRFeeScheduleDTL> SRFeeScheduleDTLs { get; set; }
        public virtual DbSet<SRFeeScheduleHdr> SRFeeScheduleHdrs { get; set; }
        public virtual DbSet<SRInvoiceDetail> SRInvoiceDetails { get; set; }
        public virtual DbSet<SRInvoiceHeader> SRInvoiceHeaders { get; set; }
        public virtual DbSet<SRReceiptsDetail> SRReceiptsDetails { get; set; }
        public virtual DbSet<SRReceiptsHeader> SRReceiptsHeaders { get; set; }
        public virtual DbSet<SRSchorlarshipSetupDtl> SRSchorlarshipSetupDtls { get; set; }
        public virtual DbSet<SRSchorlarshipSetupHdr> SRSchorlarshipSetupHdrs { get; set; }
        public virtual DbSet<SRSession> SRSessions { get; set; }
        public virtual DbSet<SRSessionsDTL> SRSessionsDTLs { get; set; }
        public virtual DbSet<SRStudent> SRStudents { get; set; }
    }
}
