//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPay.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SRClass()
        {
            this.SRClassArms = new HashSet<SRClassArm>();
        }
    
        public int RecordID { get; set; }
        public string ClassID { get; set; }
        public string Description { get; set; }
        public string BuildingID { get; set; }
        public Nullable<int> StudentsCount { get; set; }
        public string TeacherID { get; set; }
        public string PrefectID { get; set; }
        public string CategoryID { get; set; }
        public string ScaleID { get; set; }
        public Nullable<int> ClassOrder { get; set; }
        public string AuditCompanyID { get; set; }
        public string AuditUserID { get; set; }
        public Nullable<System.DateTime> AuditDatetime { get; set; }
        public string CompanyID { get; set; }
        public string DivisionID { get; set; }
        public string DepartmentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRClassArm> SRClassArms { get; set; }
    }
}
