//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPay.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRClassArm
    {
        public int RecordID { get; set; }
        public int ParentID { get; set; }
        public string Arm { get; set; }
        public Nullable<int> MaxPopulation { get; set; }
        public Nullable<int> CurrentPopulation { get; set; }
        public string ArmTeacher { get; set; }
        public string AuditCompanyID { get; set; }
        public string AuditUserID { get; set; }
        public Nullable<System.DateTime> AuditDatetime { get; set; }
        public string CompanyID { get; set; }
        public string DivisionID { get; set; }
        public string DepartmentID { get; set; }
    
        public virtual SRClass SRClass { get; set; }
    }
}
