//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPay.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRFeeScheduleDTL
    {
        public int RecordID { get; set; }
        public int ParentID { get; set; }
        public string ItemID { get; set; }
        public string LedgerAccount { get; set; }
        public double FeeAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string AuditCompanyID { get; set; }
        public string AuditUserID { get; set; }
        public string MappedItemID { get; set; }
        public double FeeFactor { get; set; }
        public string CompanyID { get; set; }
        public string DivisionID { get; set; }
        public string DepartmentID { get; set; }
    
        public virtual SRFeeScheduleHdr SRFeeScheduleHdr { get; set; }
    }
}
