//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPay.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRInvoiceDetail
    {
        public int RecordID { get; set; }
        public int ParentID { get; set; }
        public int LineNumber { get; set; }
        public string ItemID { get; set; }
        public string ItemUPCCode { get; set; }
        public string SerialNumber { get; set; }
        public string ItemUOM { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> DiscountPerc { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string GLTransAccount { get; set; }
        public string CurrencyID { get; set; }
        public Nullable<decimal> CurrencyExchangeRate { get; set; }
        public Nullable<decimal> ItemQty { get; set; }
        public Nullable<decimal> ItemCost { get; set; }
        public Nullable<decimal> ItemUnitPrice { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<System.DateTime> ScheduledStartDate { get; set; }
        public Nullable<System.DateTime> ScheduledEndDate { get; set; }
        public string DetailMemo1 { get; set; }
        public string DetailMemo2 { get; set; }
        public string AuditUserID { get; set; }
        public string AuditCompanyID { get; set; }
        public Nullable<System.DateTime> AuditDatetime { get; set; }
        public string CompanyID { get; set; }
        public string DivisionID { get; set; }
        public string DepartmentID { get; set; }
    
        public virtual SRInvoiceHeader SRInvoiceHeader { get; set; }
    }
}
