//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPay.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRReceiptsDetail
    {
        public int RecordID { get; set; }
        public int ParentID { get; set; }
        public string ReceiptID { get; set; }
        public int LineNumber { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public Nullable<decimal> DiscountTaken { get; set; }
        public Nullable<decimal> WriteOffAmount { get; set; }
        public Nullable<decimal> AppliedAmount { get; set; }
        public Nullable<bool> Cleared { get; set; }
        public string ProjectID { get; set; }
        public string DetailMemo1 { get; set; }
        public string DetailMemo2 { get; set; }
        public string AuditCompanyID { get; set; }
        public Nullable<System.DateTime> AuditDatetime { get; set; }
        public string CompanyID { get; set; }
        public string DivisionID { get; set; }
        public string DepartmentID { get; set; }
    
        public virtual SRReceiptsHeader SRReceiptsHeader { get; set; }
    }
}
