//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPay.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRReceiptsHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SRReceiptsHeader()
        {
            this.SRReceiptsDetails = new HashSet<SRReceiptsDetail>();
        }
    
        public int RecordID { get; set; }
        public string ReceiptID { get; set; }
        public string ReceiptTypeID { get; set; }
        public string ReceiptClassID { get; set; }
        public string ChequeNumber { get; set; }
        public string DepSlipNumber { get; set; }
        public string StudentID { get; set; }
        public Nullable<bool> Memorize { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public Nullable<System.DateTime> DueToDate { get; set; }
        public string CurrencyID { get; set; }
        public Nullable<double> CurrencyExchangeRate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> UnAppliedAmount { get; set; }
        public string GLBankAccount { get; set; }
        public string ReceiptNotes { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<bool> Cleared { get; set; }
        public Nullable<bool> Posted { get; set; }
        public string GLTransactionNumber { get; set; }
        public Nullable<bool> Reconciled { get; set; }
        public Nullable<bool> Deposited { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public string HeaderMemo1 { get; set; }
        public string HeaderMemo2 { get; set; }
        public string HeaderMemo3 { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string EnteredBy { get; set; }
        public string BatchControlNumber { get; set; }
        public Nullable<decimal> BatchControlTotal { get; set; }
        public string ReferenceID1 { get; set; }
        public string ReferenceID2 { get; set; }
        public string RefRevenueCode { get; set; }
        public string RefBankID { get; set; }
        public string PaidInBy { get; set; }
        public string SessionID { get; set; }
        public string TermID { get; set; }
        public string ClassID { get; set; }
        public string FacultyID { get; set; }
        public string CourseID { get; set; }
        public string CompanyID { get; set; }
        public string DivisionID { get; set; }
        public string DepartmentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRReceiptsDetail> SRReceiptsDetails { get; set; }
    }
}
