//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPay.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRSchorlarshipSetupDtl
    {
        public int RecordID { get; set; }
        public int ParentID { get; set; }
        public string CompanyID { get; set; }
        public string DivisionID { get; set; }
        public string DepartmentID { get; set; }
        public string ItemID { get; set; }
        public int LineNumber { get; set; }
        public string SchorlarshipType { get; set; }
        public double Value { get; set; }
        public Nullable<System.DateTime> AuditDateTime { get; set; }
        public string AuditCompanyID { get; set; }
        public string AuditUserID { get; set; }
    
        public virtual SRSchorlarshipSetupHdr SRSchorlarshipSetupHdr { get; set; }
    }
}
